In [1]:
# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

/home/harsh/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
dataset = pd.read_csv('BankCustomers.csv')

In [3]:
X = dataset.iloc[:, 3:13]
y = dataset.iloc[:, 13]

In [4]:
states=pd.get_dummies(X['Geography'], drop_first=True)
gender=pd.get_dummies(X['Gender'], drop_first=True)

In [5]:
X=X.drop(['Geography', 'Gender'], axis = 1)

In [6]:
X=pd.concat([X,states,gender], axis = 1)

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
sc = StandardScaler()

In [9]:
X=sc.fit_transform(X)

In [10]:
X

array([[-0.32622142,  0.29351742, -1.04175968, ..., -0.57873591,
        -0.57380915, -1.09598752],
       [-0.44003595,  0.19816383, -1.38753759, ..., -0.57873591,
         1.74273971, -1.09598752],
       [-1.53679418,  0.29351742,  1.03290776, ..., -0.57873591,
        -0.57380915, -1.09598752],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -0.57873591,
        -0.57380915, -1.09598752],
       [ 1.25683526,  0.29351742, -0.69598177, ...,  1.72790383,
        -0.57380915,  0.91241915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -0.57873591,
        -0.57380915, -1.09598752]])

In [11]:
from sklearn.decomposition import PCA

/home/harsh/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [12]:
pca = PCA(n_components=2)

In [13]:
X =pca.fit_transform(X)

In [14]:
X

array([[ 0.52681948, -0.37601399],
       [ 0.72631782, -2.09583403],
       [-0.00990015,  2.11637355],
       ...,
       [ 0.63017814, -0.4387183 ],
       [-1.08328972,  1.22948038],
       [-0.64563521,  0.01309985]])

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, Y_train, Y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

In [17]:
from sklearn.linear_model import LogisticRegression
linear = LogisticRegression()

In [18]:
X_train

array([[ 2.03594711,  0.81752231],
       [-1.5352628 , -0.61012523],
       [-0.54379077,  0.31020033],
       ...,
       [-0.49013085,  0.76587645],
       [ 2.10444595,  0.3171373 ],
       [-2.01421224,  0.22291323]])

In [19]:
linear.fit(X_train, Y_train)

/home/harsh/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [20]:
Y_pred = linear.predict(X_test)

In [21]:
Y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [22]:
Y_test.values

array([0, 1, 0, ..., 0, 0, 0])

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score,r2_score

In [68]:
confusion_matrix(Y_test,Y_pred)

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [24]:
accuracy_score(Y_test, Y_pred)

0.7975

In [25]:
r2_score(Y_test, Y_pred)

-0.2539184952978055