In [20]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np
import matplotlib.pyplot as py

In [21]:
iris = load_iris()

In [22]:
dataset= pd.DataFrame(data=np.concatenate(iris['data'],iris['target']), columns=['iris.feature_names'] + iris['target_names'])

TypeError: only integer scalar arrays can be converted to a scalar index

In [23]:
dataset = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns= iris['feature_names'] + ['target'])

In [24]:
dataset

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  
..      ...  
145     2.0  
146     2.0  
147     2.0  
148     2.0  
149     2.0  

[150 rows x 5 columns]

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
x= dataset.iloc[:,0:4]
print(x)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]


In [27]:
y=dataset['target']
print(y)

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
145    2.0
146    2.0
147    2.0
148    2.0
149    2.0
Name: target, Length: 150, dtype: float64


In [28]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.2,random_state=0)

In [32]:
from sklearn.ensemble import RandomForestClassifier
randomForestClassifier = RandomForestClassifier()

In [44]:
from sklearn.model_selection import GridSearchCV
params = dict(n_estimators = [3,4,5,6,7,8,10,22,28,31], random_state=[0])
cl = GridSearchCV(estimator=randomForestClassifier, param_grid=params, cv = 10)

In [50]:
cl.fit(X_train, y_train)
print(cl.best_params_)

{'n_estimators': 3, 'random_state': 0}


In [46]:
y_predict = cl.predict(X_test)
print()

In [47]:
from sklearn.metrics import classification_report, accuracy_score,confusion_matrix

In [48]:
print(classification_report(y_test, y_predict))
print(accuracy_score(y_test, y_predict))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        11
         1.0       0.93      1.00      0.96        13
         2.0       1.00      0.83      0.91         6

    accuracy                           0.97        30
   macro avg       0.98      0.94      0.96        30
weighted avg       0.97      0.97      0.97        30

0.9666666666666667


In [49]:
print(confusion_matrix(y_test, y_predict))

[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]


In [41]:
print(y_test)

114    2.0
62     1.0
33     0.0
107    2.0
7      0.0
100    2.0
40     0.0
86     1.0
76     1.0
71     1.0
134    2.0
51     1.0
73     1.0
54     1.0
63     1.0
37     0.0
78     1.0
90     1.0
45     0.0
16     0.0
121    2.0
66     1.0
24     0.0
8      0.0
126    2.0
22     0.0
44     0.0
97     1.0
93     1.0
26     0.0
Name: target, dtype: float64


In [52]:
from sklearn.ensemble import RandomForestClassifier
classifier  = RandomForestClassifier(n_estimators=3, random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print(accuracy_score(y_test,y_pred))

0.9666666666666667
